# ==============================================================================
# Workflow GitHub Actions pour l'Analyse Technique BRVM
# ==============================================================================
name: BRVM Technical Analysis Daily Run

on:
  schedule:
    # S'exécute tous les jours à 07h00 UTC
    - cron: '0 7 * * *'
  
  # Permet de lancer manuellement le workflow depuis l'onglet "Actions" de GitHub
  workflow_dispatch:

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code de votre dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure l'environnement Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Installe les bibliothèques Python nécessaires
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install gspread google-auth-oauthlib google-auth-httplib2 pandas numpy

      # 4. Exécute le script Python principal
      - name: Run Python Script
        env:
          # Passe le secret (que vous créerez dans GitHub) au script
          GSPREAD_SERVICE_ACCOUNT: ${{ secrets.GSPREAD_SERVICE_ACCOUNT }}
        run: python main.py
